language: groovy
sudo: false
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
notifications:
  email: false
jdk:
  - openjdk8
before_install:
  - chmod a+x gradlew
script: ./gradlew clean check --scan -s
